language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.7.8
  - DJANGO=1.8.2
install:
  - pip install -q -U pip
  - pip install -q Django==$DJANGO
  - pip install -q .
script:
  - python runtests.py
branches:
  only:
    - master
    - dev
